name : integration continue

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main 

jobs:
  backend-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE_USER: root
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: backend
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        run: mvn -version

      - name: Configure MySQL Connection
        run: |
          echo "spring.datasource.url=jdbc:mysql://127.0.0.1:3306/backend" > src/main/resources/application.properties
          echo "spring.datasource.username=root" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.MYSQL_PASSWORD }}" >> src/main/resources/application.properties

      - name: Build & test Backend
        run: mvn clean package test
        working-directory: ./com.inn.backend

      - name: Start Backend
        run: java -jar com.inn.backend/target/*.jar &

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install & Build Frontend
        run: |
          npm install
          npm run build
        working-directory: ./client

      - name: Start Frontend
        run: |
          cd client
          npx http-server dist/frontend -p 4200 &
